name: 'Validate Pull Request'
description: 'A GitHub Action to validate pull requests based on specific criteria.'
inputs:
  validations:
    description: 'List of validation types to be performed separated by commas'
    required: true
runs:
  using: 'node20'
  main: 'index.js'
